### ISSUE TITLE
lacking content

### ISSUE THREAD

**Issue by cdstelly** [flipxfx/ponway-life#1]
plz

**Comment by flipxfx** [comment]
unable to reproduce, closing

**Comment by flipxfx** [comment]
also check out https://github.com/flipxfx/ponway.life, currently working on exploring a different static site generator in js ;)

**Comment by cdstelly** [comment]
because these days you need a js generator for your react bootstrap to get an ajax dom amirite

**Comment by cdstelly** [comment]
ummm did you miss a commit to fix [#1](https://github.com/flipxfx/ponway-life/issues/1)?
